package(default_visibility = ["//visibility:public"])

config_setting(
    name = "linux_x64",
    values = {
        "cpu": "k8",
    }
)

config_setting(
    name = "linux_x86",
    values = {
        "cpu": "piii",
    }
)

config_setting(
    name = "darwin",
    values = {
        "cpu": "darwin",
    },
)

config_setting(
    name = "windows",
    values = {
        "cpu": "x64_windows",
    }
)