name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          cache-save: ${{ github.event_name != 'pull_request' }}

      - name: Test
        run: bazelisk test //...

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: bazel-testlogs-${{ github.job }}
          path: bazel-testlogs/**/test.xml
